{
 "title": "RESTfulCRUD_dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Errors / Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{endpoint!=\"/metrics\", status=~\"5..\"}[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{endpoint!=\"/metrics\"}[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile (0.50, sum(rate(http_request_duration_seconds_bucket{endpoint!=\"/metrics\"}[1m])) by (le, method))",
     "legendFormat": "{{method}} - 0.50"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile (0.95, sum(rate(http_request_duration_seconds_bucket{endpoint!=\"/metrics\"}[1m])) by (le, method))",
     "legendFormat": "{{method}} - 0.95"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile (0.99, sum(rate(http_request_duration_seconds_bucket{endpoint!=\"/metrics\"}[1m])) by (le, method))",
     "legendFormat": "{{method}} - 0.99"
    }
   ]
  },
  {
   "title": "Latency - Inf",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile (1, sum(rate(http_request_duration_seconds_bucket{endpoint!=\"/metrics\"}[1m])) by (le, method))",
     "legendFormat": "{{method}} - Inf+"
    }
   ]
  },
  {
   "title": "Status_RESTfulCRUD",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{endpoint!=\"/metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POD- memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"m\", pod=~\"restfulcrud-.*|healthcheck-.*\"} / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"m\", pod=~\"restfulcrud-.*|healthcheck-.*\"}[1m]) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "NGINX- Errors/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{endpoint!=\"/metrics\", status=~\"5..\"}[1m])) by (status)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "NGINX-RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{endpoint!=\"/metrics\"}[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX - Latency 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile (0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{endpoint!=\"/metrics\"}[1m])) by (le, method))",
     "legendFormat": "{{method}} - 0.50"
    }
   ]
  },
  {
   "title": "NGINX - Latency 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile (0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{endpoint!=\"/metrics\"}[1m])) by (le, method))",
     "legendFormat": "{{method}} - 0.95"
    }
   ]
  },
  {
   "title": "NGINX - Latency 0.99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile (0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{endpoint!=\"/metrics\"}[1m])) by (le, method))",
     "legendFormat": "{{method}} - 0.99"
    }
   ]
  },
  {
   "title": "NGINX - Latency - Inf",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile (1, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{endpoint!=\"/metrics\"}[1m])) by (le, method))",
     "legendFormat": "{{method}} - Inf+"
    }
   ]
  }
 ]
}