FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY restfulcrud.py /app/
COPY test_data.csv /app/
EXPOSE 80
CMD ["uvicorn", "restfulcrud:app", "--host", "0.0.0.0", "--port", "80"]
