apiVersion: apps/v1
kind: Deployment
metadata:
  name: restfulcrud-deployment
  namespace: m
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restfulcrud-app
  template:
    metadata:
      labels:
        app: restfulcrud-app
    spec:
      # initContainers:
      #   - name: wait-for-db
      #     image: busybox
      #     command: ['sh', '-c', 'until nc -z db-service 5432; do echo waiting for db; sleep 2; done;']
      containers:
        - name: restfulcrud
          image: andrey803/otus:restfulcrud_service
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: db-config
