apiVersion: v1
kind: Service
metadata:
  name: healthcheck-services
  namespace: m
spec:
  selector:
    app: healthcheck-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP