apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: healthcheck-app
  template:
    metadata:
      labels:
        app: healthcheck-app
    spec: 
      containers:
      - name: healthcheck
        image: andrey803/otus:healthcheck
        ports:
          - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
         exec:
          command:
          - ls
          - /var/ready
